---
title:Itsvismay.Github.Io
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/blog/:title"
name: 
description: 
google_verification: 
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
